#!/usr/bin/env bash
set -euo pipefail

./config.sh remove --local

runner_token="$(curl -Ss -X POST -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/orgs/$GITHUB_ORG/actions/runners/registration-token | jq -r .token)"

if [ -z "${GITHUB_REPO-}" ]; then
  runner_url=https://github.com/"$GITHUB_ORG"
else
  runner_url=https://github.com/"$GITHUB_ORG"/"$GITHUB_REPO"
fi

exec ./config.sh \
  --ephemeral \
  --labels "$RUNNER_LABELS" \
  --name "$RUNNER_NAME" \
  --no-default-labels \
  --replace \
  --runnergroup "$RUNNER_GROUP" \
  --token "$runner_token" \
  --unattended \
  --url "$runner_url"
