#!/usr/bin/env bash
set -euo pipefail

metadata_token="$(curl -Ss -H "X-AWS-EC2-Metadata-Token-TTL-Seconds: 60" -X PUT http://169.254.169.254/latest/api/token)"

instance_tag() {
  metadata tags/instance/"$1"
}

metadata() {
  curl -Ss -H "X-AWS-EC2-Metadata-Token: $metadata_token" http://169.254.169.254/latest/meta-data/"$1"
}

create_runner_region="$(instance_tag ActionsRunner:RunnerCreate:Region)"
create_runner_url="$(instance_tag ActionsRunner:RunnerCreate:Url)"
config="$(AWS_REGION="$create_runner_region" aws-execute-api "$create_runner_url")"

cat >/etc/actions-runner/ec2.env <<EOL
ACTIONS_RUNNER_INPUT_JITCONFIG=$config
EOL
