#!/usr/bin/env bash
set -euo pipefail

create_runner_region="$(imds tags/instance/FastActionsRunnerEc2:Create:Region)"
create_runner_url="$(imds tags/instance/FastActionsRunnerEc2:Create:Url)"
config="$(AWS_REGION="$create_runner_region" aws-execute-api "$create_runner_url")"

cat >/var/tmp/fare-create.env <<EOL
ACTIONS_RUNNER_INPUT_JITCONFIG=$config
EOL
