TARGETS = [
    "//aws/cdk-util:lib",
    "//aws/cf-resource:lib",
    "//aws/client:lib",
    "//aws/dynamodb:lib",
    "//aws/function:lib",
    "//aws/queue-to-fifo:lib",
    "//aws/sqs:lib",
    "//aws/util:lib",
    "//fare/app:lib",
    "//fare/basic-infra:lib",
    "//fare/cf-resource:lib",
    "//fare/infra:lib",
    "//fare/provision:lib",
    "//github/util:lib",
    "//github/webhook:lib",
    "//javascript/util:lib",
]
