#!/usr/bin/env bash
set -euo pipefail

action="$1"

if [ "$action" = up ]; then
  iptables -N METADATA_OUTPUT
  iptables -A OUTPUT -d 169.254.169.254 -j METADATA_OUTPUT
  for user in $METADATA_USERS; do
    iptables -A METADATA_OUTPUT -m owner --uid-owner "$user" -j ACCEPT
  done
  iptables -A METADATA_OUTPUT -j DROP
elif [ "$action" = down ]; then
  iptables -D OUTPUT -d 169.254.169.254 -j METADATA_OUTPUT
  iptables -F METADATA_OUTPUT
  iptables -X METADATA_OUTPUT
fi
