#!/usr/bin/env bash
set -euo pipefail

iptables -N METADATA_OUTPUT
iptables -A OUTPUT -d 169.254.169.254 -j METADATA_OUTPUT
for user in "$@"; do
  iptables -A METADATA_OUTPUT -m owner --uid-owner "$user" -j ACCEPT
done
iptables -A METADATA_OUTPUT -j DROP

iptables-save > /etc/iptables/rules.v4
