#!/usr/bin/env bash
set -euo pipefail

# sigv4 is used instead of curl --aws-sigv4 because the latter has bugs as of
# 8.8.0 (but fixed on master)

args=()
if IMDS_SESSION="$(imds-session)"; then
  export IMDS_SESSION
  role="$(imds iam/security-credentials)"
  token="$(imds iam/security-credentials/$role | jq -r .Token)"
  args+=(-H "X-Amz-Security-Token: $token")
fi

exec sigv4 "$@" "${args[@]}"
