#!/usr/bin/env bash
set -euo pipefail

# sigv4 is used instead of curl --aws-sigv4 because the latter has bugs as of
# 8.8.0 (but fixed on master)

metadata() {
  curl -Ss -H "X-AWS-EC2-Metadata-Token: $metadata_token" http://169.254.169.254/latest/meta-data/"$1"
}

args=()
if metadata_token="$(curl -s -H "X-AWS-EC2-Metadata-Token-TTL-Seconds: 60" --connect-timeout 1 -X PUT http://169.254.169.254/latest/api/token)"; then
  role=$(metadata iam/security-credentials)
  token=$(metadata iam/security-credentials/$role | jq -r .Token)
  args+=(-H "X-Amz-Security-Token: $token")
fi

exec sigv4 "$@" "${args[@]}"
